Release/v0.0.1
ONSdigital/sdx-rabbit-monitor pull request #1
Opened 2017-03-23 16:10 UTC by JamesGardiner

Very first release of this service. Functionality includes checking the Rabbit management console 'aliveness' and 'healthcheck' endpoints.

2017-03-24 10:42 UTC, necrophonic commented
Should have a changelog

2017-03-24 10:44 UTC, necrophonic commented
Readme should list configuration (a la https://github.com/ONSdigital/sdx-receipt-rrm) and basic install/usage

2017-03-24 11:33 UTC, tundish requested changes

2017-03-24 11:33 UTC, tundish commented on requirements.txt
> +requests==2.13.0
Also **structlog**

2017-03-24 11:33 UTC, tundish commented on rabbit_monitor.py
> +import settings
Something to consider:

If we want this to be a single-file program, we should get rid of having to import settings.py

One way to do this would be to define configuration variables as argparse options instead, and give them the default values which appear now in settings.py

A convenient way to configure for different environments is populating the CLI options from a text file:
https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars

2017-03-24 11:33 UTC, tundish commented on LICENSE.md
> +The MIT License (MIT)
This is a plain text file. Should just be called LICENSE.

2017-03-24 11:33 UTC, tundish commented on LICENSE.md
> +The MIT License (MIT)
Also, README should be README.rst. No Markdown in a Python project.

2017-03-24 11:33 UTC, tundish commented on Makefile
> +build:
It's a personal thing, but I've never liked the Makefile. There's an implicit assumption that the virtualenv is activated; it will fail otherwise. Can we get rid of it and document the CLI in README.rst?

2017-03-24 11:33 UTC, tundish commented on rabbit_monitor.py
> +
Looks wrong to have all-caps Class variables.
Lots of other ways to do it, but how about defining a namedtuple with all the settings required, then populating `self.settings` in `__init__`.

2017-03-24 11:33 UTC, tundish commented on .travis.yml
> +    - make
Maybe get rid of Makefile and put the pip install command in here.

2017-03-24 11:33 UTC, tundish commented on .travis.yml
> +- make test
Same as above. Lose the Makefile and put the unittest one-liner in here.

2017-03-24 11:33 UTC, tundish commented on rabbit_monitor.py
> +class RabbitMonitor():
This class isn't a monitor for Rabbit, it's a polling client for any web service. What makes it a check for the Rabbit service is its configuration, not its code. Let's rename it PollingMonitor or APIMonitor or something similar.

2017-03-24 11:33 UTC, tundish commented on settings.py
> +import logging
See comments above on getting rid of settings.py

2017-03-24 11:33 UTC, tundish commented on test_requirements.txt
> +six==1.10.0
Why six?

2017-03-24 11:33 UTC, tundish commented on test_requirements.txt
> +structlog==16.1.0
Structlog goes in requirements.txt

2017-03-27 13:34 UTC, JamesGardiner commented on test_requirements.txt
> +structlog==16.1.0
:white_check_mark:

2017-03-27 13:43 UTC, JamesGardiner commented on test_requirements.txt
> +six==1.10.0
No reason. Must have leaked in from global site-packages. I'll remove this.

2017-03-27 13:53 UTC, JamesGardiner commented on test_requirements.txt
> +six==1.10.0
:white_check_mark:

2017-03-27 13:53 UTC, JamesGardiner commented on requirements.txt
> +requests==2.13.0
:white_check_mark:

2017-03-27 13:54 UTC, JamesGardiner commented on rabbit_monitor.py
> +import settings
@tundish can you put this down as an issue? I'll assign it a release milestone then if we decide that's the way we want to go.

2017-03-27 13:57 UTC, JamesGardiner commented on rabbit_monitor.py
> +class RabbitMonitor():
I don't agree with this. If we had multiple polling classes, I could see the value in having them inherit from a parent `PollingMonitor` that encompassed any shared logic, but as this is quite heavily tailored for hitting the management console api, I think `RabbitMonitor` should still stand.

2017-03-27 14:21 UTC, JamesGardiner commented on rabbit_monitor.py
> +
:white_check_mark:

2017-03-27 14:29 UTC, JamesGardiner commented on LICENSE.md
> +The MIT License (MIT)
:white_check_mark:

2017-03-27 14:30 UTC, JamesGardiner commented on Makefile
> +build:
Can you open this as an issue? As above, I'll assign it to a release if we decide to go that way.

2017-03-27 14:32 UTC, JamesGardiner commented
@tundish and @necrophonic - all suggested changes made. Good to merge to master and release?

2017-03-27 16:03 UTC, necrophonic commented on .travis.yml
> +    - make
Things should be building via the makefile for consistency

2017-03-27 16:03 UTC, necrophonic commented on test_requirements.txt
> +-r requirements.txt
Looks like shouldn't be here?

2017-03-27 16:03 UTC, necrophonic commented on CHANGELOG.md
> +## Unreleased
Minor - but should be 3 hashes for consistency with other changelogs

2017-03-27 16:03 UTC, necrophonic commented on README.rst
> +sdx-rabbit-monitor
The readme should stay as markdown for consistency across repositories rather than being language specific

2017-03-27 16:03 UTC, necrophonic commented on LICENSE
> +Copyright (c) 2016 Office for National Statistics
Should be 2017

2017-03-27 16:03 UTC, necrophonic commented on README.rst
> +| RABBITMQ_HOST                   | `0.0.0.0`     | Host for the RabbitMQ service                  |
User and password vars too

2017-03-28 08:40 UTC, JamesGardiner commented on README.rst
> +| RABBITMQ_HOST                   | `0.0.0.0`     | Host for the RabbitMQ service                  |
I noticed this wasn't in the other repos... I'll raise issues there to add for consistency

2017-03-28 10:17 UTC, JamesGardiner commented on LICENSE
> +Copyright (c) 2016 Office for National Statistics
This also needs updating across repos. I'll add a card to Trello for the other services.

2017-03-28 18:55 UTC, JamesGardiner commented on CHANGELOG.md
> +## Unreleased
:white_check_mark:

2017-03-28 19:01 UTC, JamesGardiner commented on test_requirements.txt
> +-r requirements.txt
Without this `make test` fails with an opaque error if it is ever called before `make build` in the user's virtualenv. How about specifying `build` as a dependency of the `test` command in the make file, i.e.:

```
test: build
    flake8 --exclude ./lib/*
    python3 -m unittest tests/*.py
```

2017-03-28 19:05 UTC, JamesGardiner commented on LICENSE
> +Copyright (c) 2016 Office for National Statistics
:white_check_mark:

2017-03-28 19:17 UTC, necrophonic commented on test_requirements.txt
> +-r requirements.txt
That was by design to stop having to run the full install-dependencies phase every time you want to run the unit tests locally.
The readme should (though needs to be made consistent across repos) say:

```shell
make
make test
```

2017-03-29 10:17 UTC, JamesGardiner commented on test_requirements.txt
> +-r requirements.txt
:white_check_mark:

2017-03-29 10:45 UTC, tundish commented on rabbit_monitor.py
> +import settings
This is now issue #2  .

2017-03-29 10:47 UTC, tundish commented on Makefile
> +build:
Looks like opinion is divided on this one, so no action required.

2017-03-29 10:51 UTC, JamesGardiner commented on Makefile
> +build:
👍

2017-03-29 10:53 UTC, tundish approved these changes

2017-03-29 10:57 UTC, merged