adding common library logging config functionality
ONSdigital/sdx-rabbit-monitor pull request #21
Opened 2017-06-06 14:46 UTC by andrewmil

2017-06-06 14:56 UTC, andrewmil commented
looking into travis build fail now

2017-06-06 14:56 UTC, JamesGardiner requested changes

2017-06-06 14:56 UTC, JamesGardiner commented on requirements.txt
> +sdx-common>=0.4.0
0.5.1

2017-06-06 14:56 UTC, JamesGardiner commented on .travis.yml
>      - make
`make build`

2017-06-06 14:57 UTC, JamesGardiner commented
@andrewmil see my comments for what should be the fix

2017-06-06 15:01 UTC, andrewmil commented on .travis.yml
>      - make
Just spotted this as well, I pretty much copied the collect changes and didnt realise this was running slightly differently, next commit should have things sorted

2017-06-06 15:17 UTC, JamesGardiner requested changes
Can you update the README to reference the `make dev` target?

2017-06-07 08:21 UTC, JamesGardiner approved these changes

2017-06-07 08:33 UTC, merged